**Kerbal Space Program Solar System Randomizer**

Allows for a ship to use a warp drive to jump to hyperspace, arriving in a completely different system, generated by a custom seed.

Thanks to /u/Rabada over at Reddit's /r/KerbalSpaceProgram subreddit [for the idea](http://www.reddit.com/r/KerbalSpaceProgram/comments/2jcwb1/beta_than_ever_the_future_of_ksp/clcgn5j?context=3)!

Here's a list of what changes:

**Atmospheres:**  
* Atmosphere (does a body have one?)  
* Oxygen (does a body have it?)  
* Atmosphere Height  
* Atmosphere Color  
* Atmosphere Pressure

**General Planet Stuff:**  
* Gravity  
* Temperature  
* Names  

**Orbits:**  
* Reference Bodies (former moons may now orbit the sun, and former planets may orbit other planets)  
* Semi-Major Axis  
* Eccentricity  
* Inclination  
* Longitude Ascending Node  

What happens is an entirely new solar system is produced. The planets themselves are the same as the old ones, but everything about them is different.

Note that at the moment, there's no way to return the bodies to the "old" system. You have to reload the save file from KSP's main menu (and if that doesn't work, restarting KSP does for sure). You can also still launch rockets from the space center on whatever Kerbin gets turned into.

Another thing to note is that upon restart, whatever you put in orbit in the "new" system will still be in orbit on the corresponding planet/moon in the "old" system. The only thing I do is modify planets and orbits a la Hyperedit (not required to run the mod), so any vessels in orbit around a body will still be in orbit around that body afterward.

To activate the Warp Drive, just go into a solar orbit around Kerbol. Right-click on the Warp Drive part (found in the VAB under "Utility" -- it looks like an ASAS module), then click on "Activate Warp Drive." A box will come up asking for hyperspace coordinates. Type in your seed, then click the button and the system will randomize based on your seed.

**Future Additions:**  
* Return to the Kerbol System  
* Name your own planets  
* Hide vessels not in the current system  
* Custom model/Science requirement for Warp Drive
* Procedurally-generated terrain  
